name: Build
on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install Dependencies
      uses: borales/actions-yarn@v3
      with:
        cmd: install
    - name: Build
      uses: borales/actions-yarn@v3
      with:
        cmd: build
